# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

[pytest]
pythonpath       = .
testpaths        = Test
python_files     = *.py
addopts          = --ignore-glob=*_.py
python_classes   = Test*
python_functions = test_*
markers          =
    integration: marks tests as integration tests
